AWSTemplateFormatVersion: 2010-09-09
Description: Update for Photo Album Web Application - Adds IAM roles, Lambda functions, and API Gateway
Resources:
  FrontendBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: b3staticweb
      WebsiteConfiguration:
        IndexDocument: index.html
  B2Buckets:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: lambdacodebucketfinal

  IndexPhotosRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: index-photos-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: IndexPhotosLambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 'rekognition:DetectLabels'
                Resource:
                  - 'arn:aws:rekognition:*:*:image/*'

  SearchPhotosRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: search-photos-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  IndexPhotosLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: lambdacodebucketfinal
        S3Key: index-photos.zip
      Description: Index uploaded photos with labels.
      Handler: lambda_function.lambda_handler
      Role: !GetAtt IndexPhotosRole.Arn
      Runtime: python3.9
      Timeout: 30
    DependsOn:
      - IndexPhotosRole

  SearchPhotosLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: lambdacodebucketfinal
        S3Key: search-photos.zip
      Description: Search photos based on user queries.
      Handler: lambda_function.lambda_handler
      Role: !GetAtt SearchPhotosRole.Arn
      Runtime: python3.9
      Timeout: 30
    DependsOn:
      - SearchPhotosRole

  PhotoAlbumAPI:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: AI Photo Search 2
      EndpointConfiguration:
        Types:
          - REGIONAL
    DependsOn:
      - SearchPhotosLambda
Outputs:
  FrontendURL:
    Description: URL of the S3 hosted frontend website.
    Value: !GetAtt FrontendBucket.WebsiteURL
